# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12f33ac1c41bd4c0b73cc133b8db0df338e914d0f0c99dd8c52a5b48ea0a02e9eff480a8d9a2f7f704c6393c7b11943b90fa6c141a2ca8b4b69e675dd2d6aab9

test:
  secret_key_base: c17b638ccfecc0b47462972e79860a3fdfcbe61e25ed8655047771bf33d5890f307ea66cd9679242fee71ada58d5bcfc45f6f85168234f3ed1ed1be7dd0398c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
